### ISSUE TITLE
Loading spinner appears over content when navigating back

### ISSUE THREAD

**Issue by JoshMilo** [jarrodmedrano/budget2budgetfinal#1]
when you're in the expenses section and you navigate back to the enter next income/enter your next expense, the loading spinner clobbers the content.
![img_2358](https://user-images.githubusercontent.com/1663425/52526577-8ec86300-2c6f-11e9-8a38-ce13e9c810c5.png)

**Comment by jarrodmedrano** [comment]
Fixed in 84d7276c4e02603e31b2fa538c8f4786ffe2c9b7
