### ISSUE TITLE
container seems to be broken on iOS mobile

### ISSUE THREAD

**Issue by JoshMilo** [jarrodmedrano/budget2budgetfinal#2]
I think somethings breaking out of it's parent container. 
![img_2353](https://user-images.githubusercontent.com/1663425/52526586-c2a38880-2c6f-11e9-9fc2-828128d4d8f3.png)

**Comment by jarrodmedrano** [comment]
Fixed in https://github.com/jarrodmedrano/budget2budgetfinal/commit/84d7276c4e02603e31b2fa538c8f4786ffe2c9b7
